
%drawCircles draw x numbered circles on the input image 
function [ outputImage ] = drawCircles...
                                (background, fillColor, circleDimensions)

%Create the shape inserter object 
%options: fill the shape, color fill (from input), 
%         opacity and ragion of interest (ROI)
shapeInserter = ...
    vision.ShapeInserter('Shape','Circles',...
                        'Fill',true,...
                        'FillColorSource', 'Property',...
                        'FillColor', 'Custom',...
                        'CustomFillColor', fillColor,...
                        'ROIInputPort',false,...
                        'Opacity', 0.7);

%Draw the circles on the image 
I = step(shapeInserter, background, circleDimensions);

textInserter = vision.TextInserter('%d',... 
                                   'LocationSource',...
                                   'Input port',...
                                   'Color',  [255, 255, 255],...
                                   'FontSize', 18);

circleDimensions(:,3) = [];   

outputImage = step(textInserter, I,...
                   uint8([13 9 5 1 14 10 6 2 15 11 7 3 16 12 8 4]),...
                   circleDimensions);

end

%http://www.mathworks.com/help/vision/ref/vision.shapeinserter-class.html

